[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
via_ir = false
optimizer = true
optimizer_runs = 100
ffi=true
evm_version = "cancun"


remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
