[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = true
evm_version = "cancun"
fallback_oz = true
mode = "3"
gas_price = 0
block_gas_limit = 100000000
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "@poseidon2-evm/=lib/poseidon2-evm/src/"
]

[fuzz]
runs = 1000
seed = "0x2"

[invariant]
runs = 2000
depth = 128
fail_on_revert = true
