[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
via_ir = true
optimizer = true
optimizer_runs = 100
ffi=true
evm_version = "cancun"
[fuzz]
runs = 10000
seed = '0x2'

[invariant]
runs = 50000
depth = 64
fail_on_revert = true

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
