borrower_annual_revenue = ""
borrower_business_age_days = ""
borrower_commitment = ""
borrower_current_ratio = ""
borrower_debt_to_ebitda = ""
borrower_defaults_last_36_months = ""
borrower_ebitda = ""
borrower_ebitda_margin_bps = ""
borrower_has_bankruptcy = ""
borrower_interest_coverage = ""
borrower_secret = ""
borrower_tangible_net_worth = ""
industry_hash = ""
industry_is_excluded = ""
loan_apr_bps = ""
loan_origination_fee_bps = ""
loan_principal = ""
loan_term_days = ""
policy_bankruptcy_excluded = ""
policy_max_debt_to_ebitda = ""
policy_max_defaults_36_months = ""
policy_min_annual_revenue = ""
policy_min_business_age_days = ""
policy_min_current_ratio = ""
policy_min_ebitda = ""
policy_min_ebitda_margin_bps = ""
policy_min_interest_coverage = ""
policy_min_tangible_net_worth = ""
policy_version_hash = ""
tier_active = ""
tier_id = ""
tier_interest_rate_bps = ""
tier_max_debt_to_ebitda = ""
tier_max_loan_to_ebitda = ""
tier_max_revenue = ""
tier_min_ebitda = ""
tier_min_revenue = ""
tier_origination_fee_bps = ""
tier_term_days = ""
